flags: {}
extra-package-dbs: []
packages:
- .
- aradia-discord-types
- aradia-discord-rest
- aradia-discord-gateway
- aradia-discord-hs
extra-deps:
- MonadPrompt-1.0.0.5
- flexible-defaults-0.0.1.2
- log-domain-0.12
- random-fu-0.2.7.0
- random-source-0.3.0.6
- rvar-0.2.0.3
resolver: nightly-2017-11-10
